name: Resharper Code Analysis
 
on: 
    push:
        branches: [main]
 
jobs:
  resharper:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Install .NET Core
        uses: actions/setup-dotnet@v1
        with:
             dotnet-version: 3.1.101
      
      - name: Install resharper
        run: dotnet tool install -g JetBrains.ReSharper.GlobalTools
        
      - name: Add Package
        run: dotnet add AlertToCareAPI.Test/AlertToCareAPI.Test.csproj package xunit --version 2.4.0
        
      - name: Add Package
        run: dotnet add AlertToCareAPI/AlertToCareAPI.csproj package Newtonsoft.Json --version 12.0.3
        
      - name: Add Package
        run: dotnet add AlertToCareAPIUI/AlertToCareAPIUI.csproj package Newtonsoft.Json --version 12.0.3
        
      - name: Add Package
        run: dotnet add AlertToCareAPI.Test/AlertToCareAPI.Test.csproj package FluentAssertions --version 5.10.3
        
        
      - name: Add Package
        run: dotnet add AlertToCareAPI.Test/AlertToCareAPI.Test.csproj package coverlet.collector --version 1.2.0
        
      - name: Add Package
        run: dotnet add AlertToCareAPI.Test/AlertToCareAPI.Test.csproj package Microsoft.AspNetCore.TestHost --version 3.1.9
        
      - name: Add Package
        run: dotnet add AlertToCareAPI.Test/AlertToCareAPI.Test.csproj package Microsoft.NET.Test.Sdk --version 16.5.0
        
      - name: Add Package
        run: dotnet add AlertToCareAPI.Test/AlertToCareAPI.Test.csproj package xunit.runner.visualstudio --version 2.4.0
        
      - name: Run resharper inspection
        run: jb inspectcode AlertToCareAPI.sln /output=insreport.xml
       
      - name: Run resharper duplicate code check
        run: jb dupfinder AlertToCareAPI.sln /output=dupreport.xml /exclude=AlertToCareAPIUI\obj\Debug\netcoreapp3.1\LShapedLayout.g.cs /exclude=AlertToCareAPIUI\LShapedLayout.xaml.cs
       
      - name: Check Reports
        run: powershell ./resharper.ps1
